name: flutter_template
description: A Flutter Template Project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # Theming
  flex_color_scheme: ^7.3.1

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Routing
  go_router: ^13.2.0

  # Utils
  flutter_form_builder: ^9.1.1
  google_fonts: ^6.1.0
  logger: ^2.0.2+1



dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0
  custom_lint: any
  riverpod_lint: any

flutter:
  uses-material-design: true
  generate: true
